### ISSUE TITLE
hyperfreq tool cluster map bug when manually specifying reference seqs

### ISSUE THREAD

**Issue by bcclaywell** [fredhutchio/tools-fredhutch#1]
@metasoarous I was looking back over Lucie's bug report from the fall and I think there's an issue with the handling of the cluster map argument when manual specification of reference sequences is selected. See https://github.com/fredhutchio/tools-fredhutch/blob/master/tools/hyperfreq/hyperfreq.xml#L57 -- as far as I can tell, the `cluster_map` parameter isn't ever used when using reference seqs.

Also, from my understanding of the docs and your conversation with Lucie, the user should be allowed to omit the cluster map (in which case hyperfreq expects to be provided with a sequence named `all`). Is that right?

I've put together a fix to address these issues, but I'll defer to you before I merge it in.

**Comment by metasoarous** [comment]
Hey; sorry for taking a minute to get back to you. Things have been...
crazy :-)

Yeah, that all sounds right. I remember finding that some things weren't
hooked up properly after the fact, when I was starting to work on the Argo
Navis tool, and it makes sense that this issue is what Lucie was coming up
on.

Chat soon

Chris
